version: "3.8"
services:
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_DB: todo-app
      POSTGRES_USER: todo-user
      POSTGRES_PASSWORD: todo-password
    ports:
      - "5444:5432"
